#! /bin/bash

set -euxo pipefail

BASE="$(basename $(pwd))"
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

export COMPOSE_PROJECT_NAME="$BASE-$CURRENT_BRANCH"

rm -rf ./node_modules \
  && docker-compose build \
  && docker-compose run --rm tasks
